#!/bin/sh 

# update engine.js
# [the engine is borrowed from https://github.com/sebcode/prototype4]

set -e

FILES="GO.js LinkedList.js Util.js Event.js Scene.js Layer.js Timer.js VisibleEntity.js VisibleEntityGroup.js Particles.js Particle.js"

echo "// generated by updateengine.sh" > engine.js

for i in $FILES; do
	curl "https://github.com/sebcode/prototype4/raw/master/engine/$i" >> engine.js
done

